
#ifndef PARTS_CABLE_GROUND_NEW_SC_DATA_ACQUISITION_H_
#define PARTS_CABLE_GROUND_NEW_SC_DATA_ACQUISITION_H_


int sample_command(int argc, char **argv);


#endif /* PARTS_CABLE_GROUND_NEW_SC_DATA_ACQUISITION_H_ */
