#ifndef FL_THREADS_H_
#define FL_THREADS_H_

#include "thread.h"


#define GPS_THREAD_PRIORITY (8)

#define DATA_TRANSFER_PRIO (4)

#define FRAME_PARSER_PRIO (5)

#define DATA_SEND_PRIORITY  9

#define OVER_CURRENT_PRIO   (6)

#define PERIOD_DATA_PRIORITY  11

#define SEND_HERRT_BEAT_PRIORITY (8)

#define INTERNAL_AD_SAMPLE_SERV_PRIORITY 10

#endif
